### ISSUE TITLE
Hi, your project is pretty interesting. How can I have a try on it? I didn't find the design files. Thanks!

### ISSUE THREAD

**Issue by eyuszha** [surfer-rfid/surfer-rfid-wiki#1]

**Comment by keehr** [comment]
Hi, the design files are located here: https://github.com/surfer-rfid.
There is a button containing the link above at openrfidreader.net: "View on Github" that should take you there.
We plan to embed more links to the source files from the Wiki in the next few days in case this button is missed in the future.

**Comment by eyuszha** [comment]
Hi Keehr, Thanks for your quick answer. I found the design files according to your instructions above. I may have a try after I study it. Keep in touch and thanks for help! 
BR//Eric
