### ISSUE TITLE
HW sample to try?

### ISSUE THREAD

**Issue by eyuszha** [surfer-rfid/surfer-rfid-wiki#3]
Where can I buy a HW sample you did for a test and how much?

**Comment by keehr** [comment]
Currently, our hardware is not publicly available.
If we were to learn that there was substantial interest in having our project hardware made and distributed, we could look into doing a run to get a few dozen made.
For your specific needs, please write to surfer@super-semi.com and we can discuss further.

**Comment by eyuszha** [comment]
Thanks! I'll work on simulation first. Later I'll contact with you if need your support on HW build.
